# Generated by Django 4.2.4 on 2024-02-05 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('commentary', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250, verbose_name='тема')),
                ('content', models.TextField(verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Рассылка')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая рассылка')),
                ('end_date', models.DateTimeField(verbose_name='Конец рассылки')),
                ('interval', models.CharField(choices=[('once', 'разовая'), ('daily', 'ежедневно'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='once', max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('active', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=10, verbose_name='Статус')),
                ('is_activated', models.BooleanField(choices=[(True, 'Активна'), (False, 'Неактивна')], default=True, verbose_name='Активность')),
                ('mail_to', models.ManyToManyField(to='mailing.client', verbose_name='Получатели')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_datetime_sending', models.DateTimeField(auto_now=True, null=True, verbose_name='время рассылки')),
                ('status', models.CharField(blank=True, choices=[(True, 'Успешно'), (False, 'Неудача')], default=False, max_length=30, null=True, verbose_name='попытка')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
