# Generated by Django 4.2.4 on 2024-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='last_datetime_sending',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время рассылки'),
        ),
    ]
